"""
Script sinh bảng markdown từ các file _debug.txt.
Hỗ trợ cả output của check_confidence.py và webcam_infer.py.

Usage:
    python gen_md.py                          # Xử lý error_image (webcam captures)
    python gen_md.py --dir yolo_class_bbox_results  # Xử lý output check_confidence
    python gen_md.py --detailed               # Sinh bảng chi tiết confidence từng class
"""
import os
import re
import glob
import argparse
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT_DIR = SCRIPT_DIR.parent

CONF_THRESHOLD = 0.05


def parse_debug_file(txt_path):
    """Parse a _debug.txt file generated by check_confidence.py or webcam_infer.py."""
    with open(txt_path, "r", encoding="utf-8") as f:
        content = f.read()

    lines = content.strip().split("\n")
    if len(lines) < 3:
        return None

    img_name = lines[0].replace("Image:", "").strip()
    rel_dir = lines[2].replace("Relative dir:", "").strip()

    no_detection = "Không phát hiện object nào." in content

    objects = []
    current_obj = None

    for line in lines:
        # Match: Object 0 | Best: Leanbot_right (Conf: 0.9646)
        m = re.match(r"Object\s+(\d+)\s+\|\s+Best:\s+(.+?)\s+\(Conf:\s+([0-9.]+)\)", line)
        if m:
            if current_obj:
                objects.append(current_obj)
            current_obj = {
                "obj_id": int(m.group(1)),
                "best_cls": m.group(2),
                "best_conf": float(m.group(3)),
                "bbox": None,
                "class_scores": {},
            }
            continue

        # Match: Bbox (xyxy): (726.0, 880.0, 982.0, 1062.0) | Match: ...
        m = re.match(r"Bbox \(xyxy\):\s*\((.+?)\)", line)
        if m and current_obj:
            coords = tuple(int(float(x.strip())) for x in m.group(1).split(","))
            current_obj["bbox"] = coords
            continue

        # Match:   Leanbot_front: 0.0123
        # Also match:   0 - Leanbot_front: 0.0123 <-- BEST
        m = re.match(r"\s+(?:\d+\s*-\s*)?(.+?):\s+([0-9.]+)", line)
        if m and current_obj:
            name = m.group(1).strip()
            score = float(m.group(2))
            current_obj["class_scores"][name] = score
            continue

    if current_obj:
        objects.append(current_obj)

    return {
        "img_name": img_name,
        "rel_dir": rel_dir,
        "no_detection": no_detection,
        "objects": objects,
    }


def format_score(score):
    """Format a confidence score for markdown."""
    if score < CONF_THRESHOLD:
        return "< 0.05"
    return f"**{score:.4f}**"


def gen_summary_table(parsed_files):
    """Sinh bảng tóm tắt (1 dòng/ảnh) - giống gen_md.py cũ."""
    md = ["| Tên ảnh | Góc độ (Thư mục) | Số object | Nhận diện Top 1 (Class & Conf) |",
          "|---|---|---|---|"]

    for pf in parsed_files:
        if pf is None:
            continue
        if pf["no_detection"]:
            md.append(f"| {pf['img_name']} | {pf['rel_dir']} | 0 | Không có |")
        else:
            obj_count = len(pf["objects"])
            best_info = ""
            if obj_count > 0:
                obj0 = pf["objects"][0]
                best_info = f"{obj0['best_cls']} ({obj0['best_conf']:.4f})"
                if obj_count > 1:
                    best_info += f" (+ {obj_count - 1} obj khác)"
            md.append(f"| {pf['img_name']} | {pf['rel_dir']} | {obj_count} | {best_info} |")

    return "\n".join(md)


def gen_detailed_table(pf):
    """Sinh bảng chi tiết confidence cho 1 ảnh (giống format trong conversation trước)."""
    if pf is None or pf["no_detection"]:
        return "> **Không phát hiện object nào.**\n"

    objects = pf["objects"]
    if not objects:
        return "> **Không phát hiện object nào.**\n"

    # Get class names from first object
    class_names = list(objects[0]["class_scores"].keys())

    lines = []
    header = "| Vị trí | BBox (x1, y1, x2, y2) | " + " | ".join(class_names) + " | Best Class |"
    sep = "|---|---|" + "|".join(["---"] * len(class_names)) + "|---|"
    lines.append(header)
    lines.append(sep)

    for obj in objects:
        bbox = obj["bbox"]
        bbox_str = f"({bbox[0]}, {bbox[1]}, {bbox[2]}, {bbox[3]})" if bbox else "N/A"

        score_cells = []
        for cn in class_names:
            score = obj["class_scores"].get(cn, 0.0)
            score_cells.append(format_score(score))

        best_str = f"`{obj['best_cls']}` ({obj['best_conf']:.4f})"
        lines.append(f"| #{obj['obj_id']} | {bbox_str} | " + " | ".join(score_cells) + f" | {best_str} |")

    # Summary/nhận xét
    class_counts = {}
    class_confs = {}
    for obj in objects:
        cls = obj["best_cls"]
        class_counts[cls] = class_counts.get(cls, 0) + 1
        class_confs.setdefault(cls, []).append(obj["best_conf"])

    total = len(objects)
    dominant_cls = max(class_counts, key=class_counts.get)
    dominant_count = class_counts[dominant_cls]
    dominant_avg = sum(class_confs[dominant_cls]) / len(class_confs[dominant_cls])

    if dominant_count == total:
        bias = "rõ rệt"
    elif dominant_count > total / 2:
        bias = "tương đối"
    else:
        bias = "nhẹ"

    others = ", ".join(f"`{k}`: {v}/{total}" for k, v in class_counts.items() if k != dominant_cls)
    others_str = f" (phần còn lại: {others})" if others else ""

    lines.append("")
    lines.append(f"> **Nhận xét:** Bias {bias} về `{dominant_cls}` — "
                 f"{dominant_count}/{total} detection ({dominant_count * 100 // total}%), "
                 f"conf TB = {dominant_avg:.3f}{others_str}.")
    lines.append("")

    return "\n".join(lines)


def gen_webcam_report(parsed_files, detailed=False):
    """Sinh report cho webcam captures: ảnh bbox|conf + bảng chi tiết bên dưới."""
    md = ["| Ảnh BBox (Conf > 0.5) | Confidence Debug (Show all Class) |",
          "| :---: | :---: |"]

    for pf in parsed_files:
        if pf is None:
            continue

        # Extract timestamp from img_name (e.g. error_20260515_132748)
        ts_match = re.search(r"error_\d{8}_(\d{6})", pf["img_name"])
        ts = ts_match.group(1) if ts_match else pf["img_name"]
        full_ts = ts_match.group(0) if ts_match else pf["img_name"]

        # Image row
        md.append(f"| ![BBox {ts}](./error_image/{full_ts}_bbox.jpg) "
                  f"| ![Conf {ts}](./error_image/{full_ts}_conf.jpg) |")

        if detailed:
            md.append("")
            md.append(gen_detailed_table(pf))

    return "\n".join(md)


def main():
    parser = argparse.ArgumentParser(description="Sinh markdown report từ debug text files.")
    parser.add_argument("--dir", default="error_image",
                        help="Thư mục chứa _debug.txt (tương đối từ root project). Default: error_image")
    parser.add_argument("--detailed", action="store_true",
                        help="Sinh bảng chi tiết confidence từng class cho mỗi ảnh.")
    parser.add_argument("--webcam", action="store_true",
                        help="Dùng format webcam (ảnh bbox|conf). Tự bật nếu dir=error_image.")
    parser.add_argument("--from", dest="from_ts", default=None,
                        help="Lọc timestamp bắt đầu (vd: 132748)")
    parser.add_argument("--to", dest="to_ts", default=None,
                        help="Lọc timestamp kết thúc (vd: 132951)")
    parser.add_argument("--output", default=None, help="Lưu ra file (default: in ra stdout)")
    args = parser.parse_args()

    target_dir = ROOT_DIR / args.dir
    if not target_dir.exists():
        print(f"Error: {target_dir} does not exist.")
        return

    txt_files = sorted(glob.glob(str(target_dir / "**" / "*_debug.txt"), recursive=True))

    # Filter by timestamp if specified
    if args.from_ts or args.to_ts:
        filtered = []
        for txt in txt_files:
            m = re.search(r"(\d{6})_debug\.txt", os.path.basename(txt))
            if m:
                ts = m.group(1)
                if args.from_ts and ts < args.from_ts:
                    continue
                if args.to_ts and ts > args.to_ts:
                    continue
            filtered.append(txt)
        txt_files = filtered

    if not txt_files:
        print("Không tìm thấy file _debug.txt nào.")
        return

    parsed = [parse_debug_file(f) for f in txt_files]
    parsed = [p for p in parsed if p is not None]

    is_webcam = args.webcam or args.dir == "error_image"

    if is_webcam:
        result = gen_webcam_report(parsed, detailed=args.detailed)
    elif args.detailed:
        # Detailed per-image tables
        parts = []
        for pf in parsed:
            parts.append(f"##### `{pf['img_name']}`")
            parts.append(gen_detailed_table(pf))
        result = "\n".join(parts)
    else:
        result = gen_summary_table(parsed)

    if args.output:
        out_path = Path(args.output)
        out_path.write_text(result, encoding="utf-8")
        print(f"Đã lưu report vào: {out_path}")
    else:
        print(result)


if __name__ == "__main__":
    main()
